baseURL = 'https://awesome-buaa-cs.github.io/fch-tutorial/'
locale = 'zh-Hans-CN'
title = '北航软院计组教程整理'
theme = 'ananke'

[security]
allowContent = ['.*']

[markup.goldmark.renderer]
unsafe = true

[caches.images]
dir = ':cacheDir/images'
